apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd # Deve ser o mesmo namespace onde o ArgoCD está instalado
data:
  service.webhook.datadog: |
    url: https://webhook-intake.datadoghq.com/api/v2/webhook/
    headers:
      - name: DD-API-KEY
        value: $dd-api-key # Isso vai ler a chave que você salvou no secret
      - name: Content-Type
        value: application/json

  template.datadog-cd-visibility: |
    webhook:
      datadog:
        method: POST
        body: |
          {
            "service": "{{.app.metadata.name}}",
            "env": "production",
            "repository_url": "{{.app.spec.source.repoURL}}",
            "commit_sha": "{{.app.status.sync.revision}}",
            "status": "{{.app.status.operationState.phase}}"
          }

  trigger.on-deployed: |
    - when: app.status.operationState.phase in ['Succeeded', 'Failed', 'Error']
      send: [datadog-cd-visibility]