apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  # Alterado o nome do serviço para cd-visibility-webhook conforme a doc
  service.webhook.cd-visibility-webhook: |
    url: https://webhook-intake.datadoghq.com/api/v2/webhook
    headers:
      - name: "DD-CD-PROVIDER-ARGOCD"
        value: "true"
      - name: "DD-API-KEY"
        value: $dd-api-key
      - name: "Content-Type"
        value: "application/json"

  # Template oficial que envia metadados completos do commit
  template.cd-visibility-template: |
    webhook:
      cd-visibility-webhook:
        method: POST
        body: |
          {
            "app": {{toJson .app}},
            "context": {{toJson .context}},
            "service_type": {{toJson .serviceType}},
            "recipient": {{toJson .recipient}},
            "commit_metadata": {{toJson (call .repo.GetCommitMetadata .app.status.operationState.syncResult.revision)}}
          }

  # Trigger aprimorado para monitorar tanto o Sync quanto a Saúde (Health)
  trigger.cd-visibility-trigger: |
    - when: app.status.operationState.phase in ['Succeeded', 'Failed', 'Error'] and app.status.health.status in ['Healthy', 'Degraded']
      send: [cd-visibility-template]
    - when: app.status.operationState.phase == 'Running' and app.status.health.status in ['Healthy', 'Degraded']
      send: [cd-visibility-template]