apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  # SERVIÇO: Define para onde os dados serão enviados (Datadog Intake)
  service.webhook.cd-visibility-webhook: |
    url: https://webhook-intake.datadoghq.com/api/v2/webhook
    headers:
      - name: "DD-CD-PROVIDER-ARGOCD"
        value: "true" # ESSENCIAL: Identifica que o envio vem do ArgoCD para o Datadog CD Visibility
      - name: "DD-API-KEY"
        value: $dd-api-key # Busca a chave do Secret que você já configurou
      - name: "Content-Type"
        value: "application/json"

  # TEMPLATE: Formatação do JSON conforme o padrão oficial da Datadog
  template.cd-visibility-template: |
    webhook:
      cd-visibility-webhook:
        method: POST
        body: |
          {
            "app": {{toJson .app}},
            "context": {{toJson .context}},
            "service_type": {{toJson .serviceType}},
            "recipient": {{toJson .recipient}},
            "commit_metadata": {{toJson (call .repo.GetCommitMetadata .app.status.operationState.syncResult.revision)}}
          }
          # ALTERAÇÃO: .app.status.operationState.syncResult.revision
          # MOTIVO: Garante que o Datadog receba o SHA do commit que disparou o Sync atual.

  # TRIGGER: Regras de disparo (Gatilho)
  trigger.cd-visibility-trigger: |
    # ALTERAÇÃO: Adicionada a trava "app.status.operationState != nil"
    # MOTIVO: Evita o erro de log "cannot fetch phase from <nil>" quando o ArgoCD limpa o estado de operação.
    - when: app.status.operationState != nil and app.status.operationState.phase in ['Succeeded', 'Failed', 'Error'] and app.status.health.status in ['Healthy', 'Degraded']
      send: [cd-visibility-template]
    - when: app.status.operationState != nil and app.status.operationState.phase == 'Running' and app.status.health.status in ['Healthy', 'Degraded']
      send: [cd-visibility-template]