curl -X GET http://localhost:5000/api
curl -X GET http://localhost:5000/api
curl -X GET http://localhost:5000/api
curl -X GET http://localhost:5000/api
curl -X GET http://localhost:5000/api
curl -X GET http://localhost:5000/api
curl -X GET http://localhost:5000/api
curl -X GET http://localhost:5000/api/dotnet
curl -X GET http://localhost:5000/api/dotnet
curl -X GET http://localhost:5000/api/dotnet
curl -X GET http://localhost:5000/api/dotnet
curl -X GET http://localhost:5000/api/dotnet
curl -X GET http://localhost:5000/api/dotnet
