name: CI/CD - Build and Push to ECR

on:
  push:
    branches: [ main ]
    paths:
      - 'python/src/**' # Só roda se mudar o código python

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
      - name: Build and Push Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # REMOVA o 'public.ecr.aws/' daqui:
          ECR_REPOSITORY: q4s6t3k6/labs-gitops 
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Agora o comando vai montar corretamente: public.ecr.aws / q4s6t3k6/labs-gitops : tag
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./python/src
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          # O sed também vai funcionar com o caminho limpo
          sed -i "s|image: .*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" k8s/python-flask.yaml
          sed -i "s|tags.datadoghq.com/version: .*|tags.datadoghq.com/version: \"$IMAGE_TAG\"|g" k8s/python-flask.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/python-flask.yaml
          git commit -m "chore: update image and version to ${{ github.sha }} [skip ci]"
          git push origin main