name: CI/CD - Build and Push to ECR

on:
  push:
    branches: [ main ]
    paths:
      - 'python/**'       # Monitora código e Dockerfile
      - 'k8s/**'          # Monitora manifestos

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Permissões necessárias para o GitHub Actions escrever no seu repositório
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Garante que o git tenha o histórico para o push

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # ECR Public exige us-east-1 para login

      - name: Login to Amazon ECR Public
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: Build and Push Image
        env:
          ECR_REGISTRY: public.ecr.aws
          ECR_REPOSITORY: q4s6t3k6/labs-gitops
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Criamos o Short SHA (ex: 41903bb)
          SHORT_SHA=${IMAGE_TAG::7}
          
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./python
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          # 1. Atualiza a imagem com o SHA LONGO (para o Kubernetes achar o arquivo)
          sed -i "s|image:.*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" k8s/python-flask.yaml
          
          # 2. Atualiza a versão com o SHORT SHA (para o Datadog ficar bonito)
          sed -i "s|tags.datadoghq.com/version:.*|tags.datadoghq.com/version: \"$SHORT_SHA\"|g" k8s/python-flask.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Só faz o commit se houver mudanças reais no arquivo
          if [ -n "$(git status --porcelain k8s/python-flask.yaml)" ]; then
            git add k8s/python-flask.yaml
            git commit -m "chore: update image and version to ${GITHUB_SHA::7} [skip ci]"
            git push origin main
          else
            echo "Nenhuma alteração detectada no manifesto. Pulando commit."
          fi